# Generated by Django 3.0.8 on 2020-07-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='browser_title',
            field=models.CharField(default=models.CharField(max_length=300), max_length=300),
        ),
    ]
