# Generated by Django 3.0.8 on 2020-07-09 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_browser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='browser_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blog.Category'),
        ),
    ]
