# Generated by Django 3.0.8 on 2020-07-11 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200709_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ordering_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
