# Generated by Django 3.0.8 on 2020-07-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.ManyToManyField(related_name='categories', to='Blog.Category'),
        ),
    ]
