# Generated by Django 3.0.8 on 2020-07-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_post_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
