# Generated by Django 3.0.8 on 2020-07-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_remove_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorie',
            new_name='category',
        ),
    ]
